version: "3.8"

networks:
  seblak-bombom-net:
    name: seblak-bombom-net
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: seblak-bombom-db
    restart: unless-stopped
    tty: true
    ports:
      - "3330:3306"
    environment:
      MYSQL_DATABASE: seblak_bombom
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - seblak-bombom-net
  app:
    container_name: seblak-bombom-app
    build:
      context: "."
      dockerfile: Dockerfile
    image: "seblak-bombom-img"
    restart: always
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - seblak-bombom-net
