version: "3.8"

networks:
  seblak-bombom-network:
    name: seblak-bombom-network
    external: true
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: seblak-bombom-db
    restart: unless-stopped
    tty: true
    ports:
      - "3330:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - seblak-bombom-network
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    container_name: seblak-bombom-api-app
    build:
      context: "."
      dockerfile: Dockerfile
    image: "seblak-bombom-api-img"
    restart: always
    environment:
      TZ: "UTC"
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - seblak-bombom-network
    depends_on:
      mysql:
        condition: service_healthy # <-- Make sure the app only runs if MySQL is healthy.
