CREATE TABLE deliveries (
    id INTEGER AUTO_INCREMENT,
    order_id INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    distance INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders (id)
) ENGINE = InnoDB;