CREATE TABLE deliveries (
    id INTEGER AUTO_INCREMENT,
    cost FLOAT NOT NULL,
    city_name VARCHAR(255) NOT NULL,
    district_name VARCHAR(255) NOT NULL,
    village_name VARCHAR(255) NOT NULL,
    hamlet_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB;