CREATE TABLE orders (
    id INTEGER AUTO_INCREMENT,
    invoice VARCHAR(255) NOT NULL,
    product_id INTEGER NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_description TEXT NOT NULL,
    price INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    discount INTEGER NULL,
    user_id INTEGER NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    status ENUM("pending", "success", "failed") NOT NULL,
    delivery BOOLEAN NOT NULL,
    deliver_cost INTEGER NOT NULL DEFAULT 0,
    category_name VARCHAR(100) NOT NULL,
    complete_address TEXT NOT NULL,
    google_map_link TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES products (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB;