CREATE TABLE midtrans_snap_orders (
    id INTEGER AUTO_INCREMENT,
    order_id INTEGER NOT NULL,
    token TEXT NOT NULL,
    redirect_url TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders (id)
) ENGINE = InnoDB;