CREATE TABLE discounts (
    id INTEGER AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL unique,
    value INTEGER NOT NULL DEFAULT 0,
    type ENUM("percent", "nominal") NOT NULL DEFAULT "nominal",
    start TIMESTAMP NOT NULL,
    end TIMESTAMP NOT NULL,
    description TEXT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB;