CREATE TABLE addresses (
    id INTEGER AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    regency VARCHAR(100) NOT NULL,
    subdistrict VARCHAR(100) NOT NULL,
    complete_address TEXT NOT NULL, 
    google_map_link TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB;