CREATE TABLE coupon_usages (
    id INTEGER AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    coupon_id INTEGER NOT NULL,
    usage_count INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (coupon_id) REFERENCES discount_coupons (id)
) ENGINE = InnoDB;