CREATE TABLE wallets (
    id INTEGER AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    balance DECIMAL(15, 2) NOT NULL,
    status ENUM("active", "inactive") NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB;